"""Compatibility re-exports for the standalone Provider SDK contracts."""

from modular_accounting_provider_sdk.contracts import (
    CAPABILITY_METHODS,
    CAPABILITY_PARAMETERS,
    DATA_CLASSIFICATIONS,
    NETWORK_POLICIES,
    PROVIDER_SDK_VERSION,
    SUPPORTED_CAPABILITIES,
    BankProvider,
    DataClassification,
    FXProvider,
    MacroProvider,
    MarketProvider,
    NetworkPolicy,
    ProviderCapability,
    ProviderManifest,
    ProviderManifestError,
    TaxProvider,
    required_methods,
)

__all__ = [
    "CAPABILITY_METHODS",
    "CAPABILITY_PARAMETERS",
    "DATA_CLASSIFICATIONS",
    "NETWORK_POLICIES",
    "PROVIDER_SDK_VERSION",
    "SUPPORTED_CAPABILITIES",
    "BankProvider",
    "DataClassification",
    "FXProvider",
    "MacroProvider",
    "MarketProvider",
    "NetworkPolicy",
    "ProviderCapability",
    "ProviderManifest",
    "ProviderManifestError",
    "TaxProvider",
    "required_methods",
]
