"""Deterministic scaffolding for third-party provider packages."""

from __future__ import annotations

import json
import re
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent
from typing import cast

from .contracts import DataClassification, NetworkPolicy, ProviderManifest

__all__ = ["ProviderScaffold", "normalise_provider_package", "scaffold_provider"]

_PACKAGE_PATTERN = re.compile(r"^[a-z_][a-z0-9_]*$")


@dataclass(frozen=True, slots=True)
class ProviderScaffold:
    """Metadata describing generated provider package files."""

    key: str
    package: str
    module: str
    root: Path
    created_files: tuple[Path, ...]


def normalise_provider_package(key: str) -> str:
    """Return a Python package name derived from a provider key."""

    package = key.replace(":", "_").replace("-", "_")
    if _PACKAGE_PATTERN.fullmatch(package) is None:
        raise ValueError("Provider key does not produce a safe Python package name")
    return package


def _literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _tuple_literal(values: Iterable[str]) -> str:
    items = tuple(values)
    if not items:
        return "()"
    return "(" + ", ".join(_literal(value) for value in items) + ",)"


def _method_lines(capability: str) -> list[str]:
    if capability == "fx":
        return [
            '    def sync_daily_rates(self, base: str = "USD", date_: date | None = None) -> list[object]:',
            '        """Return provider-specific FX records after implementing the adapter."""',
            "",
            "        return []",
        ]
    if capability == "market":
        return [
            "    def fetch_prices(self, symbol: str, start: date, end: date) -> list[object]:",
            '        """Return provider-specific market records after implementing the adapter."""',
            "",
            "        return []",
        ]
    if capability == "tax":
        return [
            "    def upsert_rules(self) -> list[object]:",
            '        """Return provider-specific tax rules after implementing the adapter."""',
            "",
            "        return []",
        ]
    if capability == "macro":
        return [
            "    def fetch_series(self, series_id: str, start: date, end: date) -> list[tuple[date, float]]:",
            '        """Return provider-specific macro observations after implementing the adapter."""',
            "",
            "        return []",
        ]
    if capability == "bank":
        return [
            "    def list_accounts(self) -> list[dict[str, object]]:",
            '        """Return provider-specific account summaries after implementing the adapter."""',
            "",
            "        return []",
            "",
            "    def fetch_transactions(",
            "        self,",
            "        account_id: str,",
            "        start: date,",
            "        end: date,",
            "    ) -> list[dict[str, object]]:",
            '        """Return provider-specific bank transactions after implementing the adapter."""',
            "",
            "        return []",
        ]
    raise ValueError(f"Unsupported provider capability: {capability}")


def _provider_source(manifest: ProviderManifest, class_name: str) -> str:
    manifest_lines = [
        "PROVIDER_MANIFEST = ProviderManifest(",
        f"    key={_literal(manifest.key)},",
        f"    name={_literal(manifest.name)},",
        f"    version={_literal(manifest.version)},",
        f"    api_major={manifest.api_major},",
        f"    capabilities={_tuple_literal(manifest.capabilities)},",
        f"    factory={_literal(manifest.factory)},",
        f"    sdk_version={_literal(manifest.sdk_version)},",
    ]
    if manifest.description is not None:
        manifest_lines.append(f"    description={_literal(manifest.description)},")
    if manifest.homepage is not None:
        manifest_lines.append(f"    homepage={_literal(manifest.homepage)},")
    if manifest.license is not None:
        manifest_lines.append(f"    license={_literal(manifest.license)},")
    manifest_lines.extend(
        [
            f"    network_policy={_literal(manifest.network_policy)},",
            f"    credential_env={_tuple_literal(manifest.credential_env)},",
            f"    data_classification={_literal(manifest.data_classification)},",
            ")",
        ]
    )

    lines = [
        '"""Provider package generated by `python -m cli.macli provider-sdk scaffold`."""',
        "",
        "from __future__ import annotations",
        "",
        "from datetime import date",
        "",
        "from apps.provider_sdk import ProviderManifest",
        "",
        f'__version__ = "{manifest.version}"',
        "",
        *manifest_lines,
        "",
        "",
        f"class {class_name}:",
        f'    """Starter implementation for {manifest.name}."""',
        "",
        f"    name = {_literal(manifest.name)}",
    ]
    for capability in manifest.capabilities:
        lines.extend(["", *_method_lines(capability)])
    lines.extend(
        [
            "",
            "",
            f"def provider() -> {class_name}:",
            '    """Return the synchronous provider instance."""',
            "",
            f"    return {class_name}()",
            "",
        ]
    )
    return "\n".join(lines)


def _module_name(directory: Path, package: str) -> str:
    prefix = "plugins." if directory.name == "plugins" else ""
    return f"{prefix}{package}.provider"


def scaffold_provider(
    directory: Path,
    *,
    key: str,
    capabilities: Iterable[str],
    name: str | None = None,
    version: str = "0.1.0",
    api_major: int = 0,
    description: str | None = None,
    homepage: str | None = None,
    license: str | None = None,
    network_policy: str = "none",
    credential_env: Iterable[str] = (),
    data_classification: str = "controlled-sample",
    force: bool = False,
) -> ProviderScaffold:
    """Create a deterministic provider package and conformance test."""

    manifest = ProviderManifest(
        key=key,
        name=name or key.split(":", 1)[-1].replace("-", " ").replace("_", " ").title(),
        version=version,
        api_major=api_major,
        capabilities=tuple(capabilities),
        description=description,
        homepage=homepage,
        license=license,
        network_policy=cast(NetworkPolicy, network_policy),
        credential_env=tuple(credential_env),
        data_classification=cast(DataClassification, data_classification),
    )
    package = normalise_provider_package(manifest.key)
    module = _module_name(directory, package)
    target = directory / package
    known_paths = (
        target / "__init__.py",
        target / "provider.py",
        target / "README.md",
        target / "tests" / "test_conformance.py",
    )
    existing = tuple(path for path in known_paths if path.exists())
    if existing and not force:
        raise FileExistsError(f"Provider package '{package}' already contains generated files")

    (target / "tests").mkdir(parents=True, exist_ok=True)
    class_name = "".join(part.capitalize() for part in package.split("_")) + "Provider"

    init_source = dedent(
        '''\
        """Generated provider package."""

        from .provider import PROVIDER_MANIFEST, provider

        __all__ = ["PROVIDER_MANIFEST", "provider"]
        '''
    ).lstrip()
    provider_source = _provider_source(manifest, class_name)
    readme_source = dedent(
        f"""\
        # {manifest.name}

        Generated with `python -m cli.macli provider-sdk scaffold`.

        - Provider key: `{manifest.key}`
        - Import module: `{module}`
        - SDK version: `{manifest.sdk_version}`
        - Implementation version: `{manifest.version}`
        - Capabilities: `{", ".join(manifest.capabilities)}`
        - Network policy: `{manifest.network_policy}`
        - Credential environment variables: `{", ".join(manifest.credential_env) or "none"}`

        The generated implementation is intentionally non-networked and returns
        empty result collections. Replace those method bodies with bounded,
        sanitized adapter logic and retain the conformance test.
        """
    ).lstrip()
    test_source = dedent(
        f'''\
        from apps.api.version import API_VERSION
        from apps.provider_sdk import inspect_provider_module

        MODULE = "{module}"


        def test_generated_provider_conforms() -> None:
            report = inspect_provider_module(
                MODULE,
                expected_key="{manifest.key}",
                expected_capabilities={manifest.capabilities!r},
                api_version=API_VERSION,
            )

            assert report.passed, report.to_json()
        '''
    ).lstrip()

    contents = (init_source, provider_source, readme_source, test_source)
    for path, content in zip(known_paths, contents, strict=True):
        path.write_text(content, encoding="utf-8", newline="\n")

    return ProviderScaffold(
        key=manifest.key,
        package=package,
        module=module,
        root=target,
        created_files=known_paths,
    )
