"""Deterministic, bounded, and spreadsheet-safe close evidence bundles."""

from __future__ import annotations

import csv
import hashlib
import json
from dataclasses import asdict, dataclass
from datetime import date, datetime
from decimal import Decimal
from io import BytesIO, StringIO
from typing import Any, cast
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

from sqlmodel import Session, select

from ..limits import MAX_EVIDENCE_ARCHIVE_BYTES, MAX_EVIDENCE_ROWS
from ..models.models import (
    Account,
    AccountReconciliation,
    AuditAction,
    AuditLog,
    CloseEvidence,
    JournalApproval,
    VarianceReview,
)
from ..utils.csv_safety import safe_csv_text
from .close_service import CloseService, CloseValidationError
from .ledger_service import LedgerService, TrialBalanceRow


@dataclass(frozen=True, slots=True)
class EvidenceFile:
    name: str
    byte_length: int
    sha256: str


@dataclass(frozen=True, slots=True)
class EvidenceBundle:
    content: bytes
    manifest_sha256: str
    filename: str
    files: tuple[EvidenceFile, ...]
    source_version: int


def _json_default(value: Any) -> Any:
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, Decimal):
        return str(value)
    if hasattr(value, "value"):
        return value.value
    raise TypeError(f"Unsupported JSON value: {type(value).__name__}")


def _canonical_json(value: Any) -> bytes:
    return (
        json.dumps(value, default=_json_default, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode("utf-8")


def _csv_bytes(fieldnames: list[str], rows: list[dict[str, Any]]) -> bytes:
    buffer = StringIO(newline="")
    writer = csv.DictWriter(buffer, fieldnames=fieldnames, lineterminator="\n", extrasaction="ignore")
    writer.writeheader()
    for row in rows:
        writer.writerow(
            {
                key: safe_csv_text(value) if isinstance(value, str) else ("" if value is None else value)
                for key, value in row.items()
            }
        )
    return buffer.getvalue().encode("utf-8")


def _zip_info(name: str) -> ZipInfo:
    info = ZipInfo(filename=name, date_time=(1980, 1, 1, 0, 0, 0))
    info.compress_type = ZIP_DEFLATED
    info.create_system = 0
    info.external_attr = 0o600 << 16
    return info


class CloseEvidenceService:
    """Create repeatable evidence bytes without persisting archive contents."""

    def __init__(self, session: Session, organization_id: int, actor_user_id: int):
        self.s = session
        self.organization_id = organization_id
        self.actor_user_id = actor_user_id
        self.close = CloseService(session, organization_id, actor_user_id)

    def build_bundle(self, cycle_id: int) -> EvidenceBundle:
        cycle = self.close.require_cycle(cycle_id)
        period = self.close.require_period(cycle.period_id)
        readiness = self.close.readiness(cycle_id)
        # Evidence is being generated by this snapshot. Normalize the evidence
        # control inside the bundle so a subsequent download of the same
        # persisted close state is byte-for-byte identical to the generated ZIP.
        evidence_blockers = tuple(
            blocker for blocker in readiness.blockers if blocker.code != "CLOSE_EVIDENCE_NOT_CURRENT"
        )
        normalized_completed = readiness.completed_required_count
        if readiness.evidence_freshness != "CURRENT":
            normalized_completed = min(readiness.required_task_count, normalized_completed + 1)
        normalized_ratio = (
            Decimal(normalized_completed) / Decimal(readiness.required_task_count)
            if readiness.required_task_count
            else Decimal("1")
        )
        trial_balance = LedgerService(self.s, self.organization_id).trial_balance(end_date=period.end_date)
        trial_rows = cast(list[TrialBalanceRow], trial_balance["rows"])
        reconciliations = list(
            self.s.exec(
                select(AccountReconciliation)
                .where(
                    AccountReconciliation.organization_id == self.organization_id,
                    AccountReconciliation.cycle_id == cycle_id,
                )
                .order_by(cast(Any, AccountReconciliation.account_id))
            )
        )
        variances = list(
            self.s.exec(
                select(VarianceReview)
                .where(VarianceReview.organization_id == self.organization_id, VarianceReview.cycle_id == cycle_id)
                .order_by(cast(Any, VarianceReview.period_start), cast(Any, VarianceReview.account_id))
            )
        )
        approvals = list(
            self.s.exec(
                select(JournalApproval)
                .where(JournalApproval.organization_id == self.organization_id, JournalApproval.cycle_id == cycle_id)
                .order_by(cast(Any, JournalApproval.id))
            )
        )
        checklist = self.close.list_checklist(cycle_id)
        audit_entries = list(
            self.s.exec(
                select(AuditLog)
                .where(
                    AuditLog.actor_org_id == self.organization_id,
                    cast(Any, AuditLog.entity_name).in_(
                        [
                            "AccountingPeriod",
                            "CloseCycle",
                            "CloseChecklistTask",
                            "AccountReconciliation",
                            "VarianceReview",
                            "JournalApproval",
                            "StagedTransaction",
                            "Transaction",
                        ]
                    ),
                )
                .order_by(cast(Any, AuditLog.id))
            )
        )
        row_count = len(trial_rows) + len(reconciliations) + len(variances) + len(approvals) + len(checklist)
        if row_count > MAX_EVIDENCE_ROWS:
            raise CloseValidationError("Close evidence exceeds the maximum row count")

        account_names = {
            account.id: {"code": account.code, "name": account.name}
            for account in self.s.exec(select(Account).where(Account.organization_id == self.organization_id))
        }
        files: dict[str, bytes] = {
            "close-cycle.json": _canonical_json(
                {
                    "cycle": {
                        "id": cycle.id,
                        "name": cycle.name,
                        "status": cycle.status,
                        "owner_user_id": cycle.owner_user_id,
                        "due_date": cycle.due_date,
                        "policy": cycle.policy,
                        "version": cycle.version,
                        "started_at": cycle.started_at,
                        "readiness_at": cycle.readiness_at,
                        "approved_at": cycle.approved_at,
                        "closed_at": cycle.closed_at,
                        "cancelled_at": cycle.cancelled_at,
                        "reopened_at": cycle.reopened_at,
                    },
                    "period": {
                        "id": period.id,
                        "label": period.label,
                        "start_date": period.start_date,
                        "end_date": period.end_date,
                        "status": period.status,
                        "version": period.version,
                    },
                }
            ),
            "readiness.json": _canonical_json(
                {
                    **asdict(readiness),
                    "completed_required_count": normalized_completed,
                    "completion_ratio": str(normalized_ratio),
                    "blocker_count": len(evidence_blockers),
                    "blockers": [asdict(blocker) for blocker in evidence_blockers],
                    "evidence_freshness": "CURRENT",
                }
            ),
            "trial-balance.csv": _csv_bytes(
                ["account_id", "account_code", "account_name", "currency", "debit", "credit", "balance"],
                [
                    {
                        "account_id": row.account_id,
                        "account_code": row.account_code,
                        "account_name": row.account_name,
                        "currency": row.currency,
                        "debit": str(row.debit),
                        "credit": str(row.credit),
                        "balance": str(row.balance),
                    }
                    for row in sorted(trial_rows, key=lambda item: item.account_id)
                ],
            ),
            "reconciliations.csv": self._reconciliation_csv(reconciliations, account_names),
            "reconciliation-exceptions.csv": self._reconciliation_csv(
                [item for item in reconciliations if item.status.value in {"EXCEPTION", "IN_PROGRESS"}],
                account_names,
            ),
            "variance-reviews.csv": _csv_bytes(
                [
                    "id",
                    "budget_id",
                    "account_id",
                    "period_start",
                    "budget_amount",
                    "actual_amount",
                    "variance_amount",
                    "variance_percent",
                    "is_material",
                    "disposition",
                    "reviewer_user_id",
                    "note",
                ],
                [
                    {
                        "id": row.id,
                        "budget_id": row.budget_id,
                        "account_id": row.account_id,
                        "period_start": row.period_start.isoformat(),
                        "budget_amount": str(row.budget_amount),
                        "actual_amount": str(row.actual_amount),
                        "variance_amount": str(row.variance_amount),
                        "variance_percent": str(row.variance_percent) if row.variance_percent is not None else None,
                        "is_material": row.is_material,
                        "disposition": row.disposition.value,
                        "reviewer_user_id": row.reviewer_user_id,
                        "note": row.note,
                    }
                    for row in variances
                ],
            ),
            "journal-approvals.csv": _csv_bytes(
                [
                    "id",
                    "transaction_id",
                    "staged_transaction_id",
                    "requestor_user_id",
                    "status",
                    "requested_at",
                    "decided_by_id",
                    "decided_at",
                    "reason",
                    "version",
                ],
                [
                    {
                        "id": row.id,
                        "transaction_id": row.transaction_id,
                        "staged_transaction_id": row.staged_transaction_id,
                        "requestor_user_id": row.requestor_user_id,
                        "status": row.status.value,
                        "requested_at": row.requested_at.isoformat(),
                        "decided_by_id": row.decided_by_id,
                        "decided_at": row.decided_at.isoformat() if row.decided_at else None,
                        "reason": row.reason,
                        "version": row.version,
                    }
                    for row in approvals
                ],
            ),
            "checklist.csv": _csv_bytes(
                [
                    "id",
                    "task_key",
                    "title",
                    "category",
                    "required",
                    "control_type",
                    "status",
                    "owner_user_id",
                    "due_date",
                    "completed_by_id",
                    "completed_at",
                    "notes",
                    "version",
                ],
                [
                    {
                        "id": row.id,
                        "task_key": row.task_key,
                        "title": row.title,
                        "category": row.category,
                        "required": row.required,
                        "control_type": row.control_type.value,
                        "status": row.status.value,
                        "owner_user_id": row.owner_user_id,
                        "due_date": row.due_date.isoformat() if row.due_date else None,
                        "completed_by_id": row.completed_by_id,
                        "completed_at": row.completed_at.isoformat() if row.completed_at else None,
                        "notes": row.notes,
                        "version": row.version,
                    }
                    for row in checklist
                ],
            ),
            "audit-references.csv": _csv_bytes(
                ["id", "timestamp", "action", "entity_name", "entity_id", "actor_user_id", "request_id", "event"],
                [
                    {
                        "id": row.id,
                        "timestamp": row.ts.isoformat(),
                        "action": row.action.value,
                        "entity_name": row.entity_name,
                        "entity_id": row.entity_id,
                        "actor_user_id": row.actor_user_id,
                        "request_id": row.request_id,
                        "event": (row.context or {}).get("event"),
                    }
                    for row in audit_entries
                ],
            ),
            "provenance.json": _canonical_json(
                {
                    "product": "Modular Accounting Toolkit",
                    "feature": "v0.2 accountant close workspace",
                    "organization_id": self.organization_id,
                    "cycle_id": cycle_id,
                    "source_version": cycle.version,
                    "period_end": period.end_date,
                    "calculation_policy": {
                        "reconciliation_difference": "control_balance - ledger_ending_balance",
                        "ledger_ending_balance": "debits - credits through inclusive period end",
                    },
                    "limitations": [
                        "Early Beta / Portfolio Preview",
                        "Not a production close certification",
                        "No automatic bank matching",
                    ],
                }
            ),
        }
        file_entries = tuple(
            EvidenceFile(name=name, byte_length=len(content), sha256=hashlib.sha256(content).hexdigest())
            for name, content in sorted(files.items())
        )
        manifest_bytes = _canonical_json(
            {
                "cycle_id": cycle_id,
                "source_version": cycle.version,
                "files": [asdict(entry) for entry in file_entries],
            }
        )
        manifest_sha = hashlib.sha256(manifest_bytes).hexdigest()
        all_files = {"manifest.json": manifest_bytes, **files}
        output = BytesIO()
        with ZipFile(output, "w", compression=ZIP_DEFLATED, compresslevel=9) as archive:
            for name in ["manifest.json", *sorted(files)]:
                archive.writestr(_zip_info(name), all_files[name])
        content = output.getvalue()
        if len(content) > MAX_EVIDENCE_ARCHIVE_BYTES:
            raise CloseValidationError("Close evidence exceeds the maximum archive size")
        label = "".join(character.lower() if character.isalnum() else "-" for character in period.label).strip("-")
        safe_label = (label or f"period-{period.id}")[:80]
        return EvidenceBundle(
            content=content,
            manifest_sha256=manifest_sha,
            filename=f"close-evidence-{safe_label}-cycle-{cycle_id}.zip",
            files=file_entries,
            source_version=cycle.version,
        )

    @staticmethod
    def _reconciliation_csv(
        reconciliations: list[AccountReconciliation], account_names: dict[int | None, dict[str, Any]]
    ) -> bytes:
        return _csv_bytes(
            [
                "id",
                "account_id",
                "account_code",
                "account_name",
                "ledger_ending_balance",
                "control_balance",
                "difference",
                "tolerance",
                "status",
                "prepared_by_id",
                "approved_by_id",
                "notes",
                "version",
            ],
            [
                {
                    "id": row.id,
                    "account_id": row.account_id,
                    "account_code": account_names.get(row.account_id, {}).get("code"),
                    "account_name": account_names.get(row.account_id, {}).get("name"),
                    "ledger_ending_balance": str(row.ledger_ending_balance),
                    "control_balance": str(row.control_balance) if row.control_balance is not None else None,
                    "difference": str(row.difference) if row.difference is not None else None,
                    "tolerance": str(row.tolerance),
                    "status": row.status.value,
                    "prepared_by_id": row.prepared_by_id,
                    "approved_by_id": row.approved_by_id,
                    "notes": row.notes,
                    "version": row.version,
                }
                for row in reconciliations
            ],
        )

    def record_generation(self, cycle_id: int, bundle: EvidenceBundle, *, summary: str | None = None) -> CloseEvidence:
        cycle = self.close.require_cycle(cycle_id)
        if bundle.source_version != cycle.version:
            raise CloseValidationError("Evidence source version no longer matches the close cycle")
        record = CloseEvidence(
            organization_id=self.organization_id,
            cycle_id=cycle_id,
            generated_by_id=self.actor_user_id,
            manifest_sha256=bundle.manifest_sha256,
            source_version=bundle.source_version,
            summary=summary.strip() if summary else None,
        )
        self.s.add(record)
        self.s.flush()
        # The evidence row itself changes readiness freshness from MISSING to
        # CURRENT. Rebuild inside the same transaction so the persisted
        # manifest describes the canonical post-generation snapshot that the
        # download endpoint will reproduce.
        authoritative_bundle = self.build_bundle(cycle_id)
        record.manifest_sha256 = authoritative_bundle.manifest_sha256
        self.s.add(record)
        self.close._audit(
            AuditAction.CREATE,
            "CloseEvidence",
            record.id,
            after={
                "cycle_id": cycle_id,
                "manifest_sha256": authoritative_bundle.manifest_sha256,
                "source_version": bundle.source_version,
                "archive_bytes": len(authoritative_bundle.content),
            },
            event="close_evidence_generated",
        )
        self.s.commit()
        self.s.refresh(record)
        return record

    def preview(self, cycle_id: int) -> dict[str, Any]:
        cycle = self.close.require_cycle(cycle_id)
        latest = self.s.exec(
            select(CloseEvidence)
            .where(CloseEvidence.organization_id == self.organization_id, CloseEvidence.cycle_id == cycle_id)
            .order_by(cast(Any, CloseEvidence.id).desc())
        ).first()
        return {
            "cycle_id": cycle_id,
            "source_version": cycle.version,
            "deterministic_files": [
                "manifest.json",
                "close-cycle.json",
                "readiness.json",
                "trial-balance.csv",
                "reconciliations.csv",
                "reconciliation-exceptions.csv",
                "variance-reviews.csv",
                "journal-approvals.csv",
                "checklist.csv",
                "audit-references.csv",
                "provenance.json",
            ],
            "latest_manifest_sha256": latest.manifest_sha256 if latest else None,
            "freshness": (
                "CURRENT" if latest and latest.source_version == cycle.version else ("STALE" if latest else "MISSING")
            ),
            "maximum_archive_bytes": MAX_EVIDENCE_ARCHIVE_BYTES,
            "maximum_rows": MAX_EVIDENCE_ROWS,
        }


__all__ = ["CloseEvidenceService", "EvidenceBundle", "EvidenceFile"]
