"""Installable Provider Author Kit public surface."""

from .compatibility import (
    SCAFFOLD_VERSION,
    SDK_DISTRIBUTION_VERSION,
    CompatibilityResult,
    application_api_major,
    check_compatibility,
)
from .conformance import (
    ConformanceCheck,
    ConformingProvider,
    ProviderConformanceError,
    ProviderConformanceReport,
    inspect_provider_module,
    load_conforming_provider,
)
from .contracts import (
    CAPABILITY_METHODS,
    CAPABILITY_PARAMETERS,
    DATA_CLASSIFICATIONS,
    NETWORK_POLICIES,
    PROVIDER_SDK_VERSION,
    SUPPORTED_CAPABILITIES,
    BankProvider,
    DataClassification,
    FXProvider,
    MacroProvider,
    MarketProvider,
    NetworkPolicy,
    ProviderCapability,
    ProviderManifest,
    ProviderManifestError,
    TaxProvider,
    required_methods,
)
from .evidence import ArtifactEvidence, artifact_evidence, sha256_file
from .scaffold import (
    ProviderProjectScaffold,
    ProviderScaffold,
    normalise_distribution_name,
    normalise_provider_package,
    scaffold_project,
    scaffold_provider,
)

__all__ = [
    "CAPABILITY_METHODS",
    "CAPABILITY_PARAMETERS",
    "DATA_CLASSIFICATIONS",
    "NETWORK_POLICIES",
    "PROVIDER_SDK_VERSION",
    "SCAFFOLD_VERSION",
    "SDK_DISTRIBUTION_VERSION",
    "SUPPORTED_CAPABILITIES",
    "ArtifactEvidence",
    "BankProvider",
    "CompatibilityResult",
    "ConformanceCheck",
    "ConformingProvider",
    "DataClassification",
    "FXProvider",
    "MacroProvider",
    "MarketProvider",
    "NetworkPolicy",
    "ProviderCapability",
    "ProviderConformanceError",
    "ProviderConformanceReport",
    "ProviderManifest",
    "ProviderManifestError",
    "ProviderProjectScaffold",
    "ProviderScaffold",
    "TaxProvider",
    "application_api_major",
    "artifact_evidence",
    "check_compatibility",
    "inspect_provider_module",
    "load_conforming_provider",
    "normalise_distribution_name",
    "normalise_provider_package",
    "required_methods",
    "scaffold_project",
    "scaffold_provider",
    "sha256_file",
]
