"""Utilities for generating extension scaffolding."""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

__all__ = ["ExtensionScaffold", "normalise_package_name", "scaffold_extension"]


_KEY_PATTERN = re.compile(r"^[a-z0-9]+:[a-z0-9]+(?:-[a-z0-9]+)*$")
_SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


@dataclass(slots=True)
class ExtensionScaffold:
    """Metadata about generated extension files."""

    key: str
    package: str
    root: Path
    created_files: tuple[Path, ...]


def normalise_package_name(key: str) -> str:
    """Return a valid Python package name derived from ``key``."""

    return key.replace(":", "_").replace("-", "_")


def _validate_key(key: str) -> None:
    if not _KEY_PATTERN.match(key):
        raise ValueError("Extension key must follow 'namespace:slug' using lowercase letters, numbers, and hyphens.")


def _format_capabilities(capabilities: Iterable[str]) -> str:
    values = tuple(cap.strip() for cap in capabilities if cap.strip())
    return "(" + ", ".join(f'"{value}"' for value in values) + ",)" if values else "()"


def scaffold_extension(
    directory: Path,
    *,
    key: str,
    name: str | None = None,
    version: str = "0.1.0",
    description: str | None = None,
    capabilities: Iterable[str] = (),
    author: str | None = None,
    force: bool = False,
    observability_contract: bool = False,
) -> ExtensionScaffold:
    """Create a new extension package skeleton."""

    _validate_key(key)
    package = normalise_package_name(key)
    if not _SLUG_PATTERN.match(package.replace("_", "-")):
        raise ValueError("Derived package name contains unsupported characters.")

    target = directory / package
    if target.exists() and not force:
        raise FileExistsError(f"Extension package '{package}' already exists")

    target.mkdir(parents=True, exist_ok=True)

    init_file = target / "__init__.py"
    init_file.write_text(
        dedent(
            '''
            """Extension package generated by `macli scaffold-extension`."""

            from .extension import register

            __all__ = ["register"]
            '''
        ).lstrip()
    )

    safe_name = name or key.split(":", 1)[-1].replace("-", " ").title()
    capabilities_literal = _format_capabilities(capabilities)
    manifest_lines = [
        "MANIFEST = ExtensionManifest(",
        f'    key="{key}",',
        f'    name="{safe_name}",',
        f'    version="{version}",',
    ]
    if description:
        manifest_lines.append(f'    description="{description}",')
    manifest_lines.append(f"    capabilities={capabilities_literal},")
    if author:
        manifest_lines.append(f'    author="{author}",')
    manifest_lines.append(")")

    extension_lines = [
        '"""Auto-generated extension entrypoint."""',
        "",
        "from __future__ import annotations",
        "",
        "from datetime import UTC, datetime",
        "",
        "from apps.extensions import ExtensionManifest, ExtensionRegistry",
    ]
    if observability_contract:
        extension_lines.append("from apps.extensions.contracts import ExtensionContract")
    extension_lines.append("from apps.observability.health import HealthReport")
    extension_lines.append("")
    extension_lines.extend(manifest_lines)
    extension_lines.extend(["", ""])

    if observability_contract:
        extension_lines.extend(
            [
                "PLAYBOOK_CONTRACT = ExtensionContract(",
                '    kind="observability:incident-playbook",',
                f'    name="{safe_name} Incident Playbook",',
                '    version="1.0",',
                '    description="Starter incident response playbook for generated extensions.",',
                f'    entrypoint="{package}.extension:get_playbook",',
                '    tags=("observability", "operations"),',
                ")",
                "",
                "",
                "def get_playbook() -> list[dict[str, str]]:",
                '    """Return a starter incident response playbook."""',
                "",
                "    return [",
                "        {",
                '            "step": "database",',
                '            "action": "Verify database connectivity and pending migrations.",',
                "        },",
                "        {",
                '            "step": "metrics",',
                '            "action": "Confirm Prometheus scrapes and exporter uptime.",',
                "        },",
                "    ]",
                "",
                "",
            ]
        )

    extension_lines.extend(
        [
            "def _health_probe() -> HealthReport:",
            "    return HealthReport(",
            '        name=f"extension:{MANIFEST.key}",',
            "        healthy=True,",
            '        severity="info",',
            "        details={",
            '            "generated_at": datetime.now(tz=UTC).isoformat(),',
            '            "exporter": "scaffold",',
            "        },",
            "    )",
            "",
            "",
        ]
    )

    register_lines = [
        "def register(registry: ExtensionRegistry) -> None:",
        '    """Register the generated extension with the registry."""',
        "",
        "    registry.register(MANIFEST)",
    ]
    if observability_contract:
        register_lines.append("    registry.register_contract(MANIFEST.key, PLAYBOOK_CONTRACT)")
    register_lines.append('    registry.register_health_check(MANIFEST.key, _health_probe, severity="info")')
    extension_lines.extend(register_lines)

    extension_file = target / "extension.py"
    extension_file.write_text(dedent("\n".join(extension_lines)).lstrip())

    readme_file = target / "README.md"
    readme_file.write_text(
        dedent(
            f"""
            # {safe_name}

            Generated via `macli scaffold-extension`. Customise `extension.py` to
            register additional health checks, metrics, or background tasks.
            """
        ).lstrip()
    )

    created = (init_file, extension_file, readme_file)
    return ExtensionScaffold(key=key, package=package, root=target, created_files=created)
