"""Snapshot diagnostics utilities for modular accounting workflows."""

from __future__ import annotations

from collections.abc import Callable, Iterable
from dataclasses import dataclass
from datetime import UTC, date, datetime

from .snapshots import DataSnapshot, SnapshotRequest


@dataclass(slots=True)
class SnapshotDiagnostics:
    """Aggregate health indicators derived from a :class:`DataSnapshot`."""

    base_currency: str | None
    fx_rate_count: int
    fx_pairs: tuple[str, ...]
    fx_max_age_seconds: float | None
    commodity_quote_count: int
    commodity_symbols: tuple[str, ...]
    commodity_max_age_seconds: float | None
    tax_rule_count: int
    active_tax_rule_count: int
    tax_jurisdictions: tuple[str, ...]
    missing_sections: tuple[str, ...]

    def has_missing_sections(self) -> bool:
        """Return ``True`` when any data category was absent in the snapshot."""

        return bool(self.missing_sections)


def compute_snapshot_diagnostics(
    snapshot: DataSnapshot,
    *,
    request: SnapshotRequest | None = None,
    now: Callable[[], datetime] | None = None,
    today: Callable[[], date] | None = None,
) -> SnapshotDiagnostics:
    """Return a :class:`SnapshotDiagnostics` view for ``snapshot``.

    Parameters
    ----------
    snapshot:
        Snapshot generated by :class:`DataSnapshotService`.
    request:
        Optional request payload used to build the snapshot. When omitted the
        diagnostics fall back to inspecting the snapshot itself to derive base
        currency and tax jurisdictions.
    now:
        Callable returning the current timestamp. Defaults to UTC ``datetime``
        instances and exists primarily for tests.
    today:
        Callable returning the current date. Defaults to :func:`date.today` and
        is also useful when writing deterministic tests.
    """

    now_fn = now or (lambda: datetime.now(tz=UTC))
    today_fn = today or date.today

    base_currency = _resolve_base_currency(snapshot, request)
    fx_pairs = _unique_pairs(rate_strings(snapshot.fx_rates))
    fx_rate_count = len(snapshot.fx_rates)
    fx_max_age_seconds = _max_age_seconds(snapshot.fx_rates, now_fn)

    commodity_symbols = _unique_pairs(quote.symbol for quote in snapshot.commodity_quotes)
    commodity_quote_count = len(snapshot.commodity_quotes)
    commodity_max_age_seconds = _max_age_seconds(snapshot.commodity_quotes, now_fn)

    tax_jurisdictions = _unique_pairs(rule.jurisdiction for rule in snapshot.tax_rules if rule.jurisdiction)
    tax_rule_count = len(snapshot.tax_rules)
    active_tax_rule_count = _count_active_rules(snapshot.tax_rules, today_fn)

    missing_sections: list[str] = []
    if fx_rate_count == 0:
        missing_sections.append("fx")
    if commodity_quote_count == 0:
        missing_sections.append("commodities")
    if tax_rule_count == 0:
        missing_sections.append("tax")

    return SnapshotDiagnostics(
        base_currency=base_currency,
        fx_rate_count=fx_rate_count,
        fx_pairs=fx_pairs,
        fx_max_age_seconds=fx_max_age_seconds,
        commodity_quote_count=commodity_quote_count,
        commodity_symbols=commodity_symbols,
        commodity_max_age_seconds=commodity_max_age_seconds,
        tax_rule_count=tax_rule_count,
        active_tax_rule_count=active_tax_rule_count,
        tax_jurisdictions=tax_jurisdictions,
        missing_sections=tuple(missing_sections),
    )


def rate_strings(rates: Iterable[object]) -> Iterable[str]:
    """Yield canonical string representations for FX rate pairs."""

    for rate in rates:
        base = getattr(rate, "base_currency", None)
        quote = getattr(rate, "quote_currency", None)
        if base is None or quote is None:
            continue
        yield f"{base}/{quote}"


def _resolve_base_currency(snapshot: DataSnapshot, request: SnapshotRequest | None) -> str | None:
    if request is not None:
        return request.base_currency
    if snapshot.fx_rates:
        return snapshot.fx_rates[0].base_currency
    return None


def _unique_pairs(items: Iterable[str]) -> tuple[str, ...]:
    seen: dict[str, None] = {}
    for item in items:
        if item and item not in seen:
            seen[item] = None
    return tuple(seen.keys())


def _max_age_seconds(values: Iterable[object], now_fn: Callable[[], datetime]) -> float | None:
    ages: list[float] = []
    reference = _normalise_datetime(now_fn())
    for value in values:
        as_of = getattr(value, "as_of", None)
        if as_of is None:
            continue
        try:
            ages.append((reference - _normalise_datetime(as_of)).total_seconds())
        except Exception:
            continue
    if not ages:
        return None
    return max(ages)


def _normalise_datetime(moment: datetime) -> datetime:
    if moment.tzinfo is None:
        return moment.replace(tzinfo=None)
    return moment.astimezone(UTC).replace(tzinfo=None)


def _count_active_rules(rules: Iterable[object], today_fn: Callable[[], date]) -> int:
    today_value = today_fn()
    active = 0
    for rule in rules:
        start = getattr(rule, "effective_from", None)
        end = getattr(rule, "effective_to", None)
        if start is None:
            continue
        if start > today_value:
            continue
        if end is not None and end < today_value:
            continue
        active += 1
    return active
